/**
 * ConnectorCodeGenerator.ts — MemoryOS Connector SDK v1.0
 * Beta-03 · 2026-07-13
 *
 * Generates TypeScript source code for a new Production Connector from a manifest.
 * Output is pure structure — no provider logic, no credentials, no business logic.
 * The developer fills in only the _dispatch() operation handlers.
 */

import type { ConnectorManifest, CapabilityDeclaration } from "./SDKTypes";

function cap(s: string) { return s.charAt(0).toUpperCase() + s.slice(1); }
function className(id: string) { return id.split(/[-_]/).map(cap).join("") + "Connector"; }

export class ConnectorCodeGenerator {

  /** Generate the main connector TypeScript file. */
  generateConnector(manifest: ConnectorManifest): string {
    const cls    = className(manifest.id);
    const capIds = manifest.capabilities.map(c => `    { id: "${c.id}", type: "${c.type}", description: "${c.description}", requiredAuth: ${c.requiredAuth}, readOnly: ${c.readOnly}, paginated: ${c.paginated} }`).join(",\n");
    const cases  = manifest.supportedOperations.map(op => `      case "${op}": {\n        // TODO: implement ${op}\n        return ok({ operation: "${op}", implemented: false }, start, eid, logs, operation);\n      }`).join("\n\n");
    const authCfg = this._authConfig(manifest);

    return `/**
 * ${cls}.ts — ${manifest.name}
 * Generated by MemoryOS Connector SDK v1.0
 * Provider: ${manifest.provider} · Auth: ${manifest.authType} · PCS v1.0
 *
 * GENERATED STRUCTURE — Fill in the _dispatch() operation handlers.
 * Do not modify the PCS infrastructure above the _dispatch() method.
 */

import type { IConnector } from "@/lib/connector-runtime/IConnector";
import type {
  ConnectorContext, ConnectorHealthReport, ConnectorMetadata,
  ConnectorResult, ConnectorLog, ConnectorValidationResult,
} from "@/lib/connector-runtime/ConnectorTypes";
import { makeLog, makeExecutionId } from "@/lib/connector-runtime/ConnectorTypes";
import type { IProductionConnector, AuthResult, AuthenticationDiagnostics, ExecutionLogEntry, AuthorizationResult } from "@/lib/production-connector-standard/IProductionConnector";
import type {
  ConnectorCapability, ConnectorHealth, ConnectorMetrics, ConnectorPermissions,
  ConnectorDiagnostics, ConnectorValidation, ConnectorAvailability, ConnectorLatency,
  ConnectorCertification, DiagnosticEntry,
} from "@/lib/production-connector-standard/PCSTypes";
import { CERTIFICATION_LABELS } from "@/lib/production-connector-standard/PCSTypes";
import { ProductionComplianceValidator } from "@/lib/production-connector-standard/ProductionComplianceValidator";

// ── Capabilities ─────────────────────────────────────────────────────────────

const CAPABILITIES: ConnectorCapability[] = [
${capIds},
];

// ── Result helpers ────────────────────────────────────────────────────────────

function ok<T>(data: T, start: number, eid: string, logs: ConnectorLog[], op: string): ConnectorResult<T> {
  const duration = Date.now() - start;
  logs.push(makeLog("info", \`[\${op}] Completed in \${duration}ms\`));
  return { status: "SUCCESS", success: true, data, duration, connectorId: "${manifest.id}", executionId: eid, logs };
}
function fail(error: string, cat: "validation" | "auth" | "external" | "internal", start: number, eid: string, logs: ConnectorLog[], op: string): ConnectorResult {
  const duration = Date.now() - start;
  logs.push(makeLog("error", \`[\${op}] FAILED [\${cat}] \${error}\`));
  return { status: "FAILED", success: false, error: \`[\${cat}] \${error}\`, duration, connectorId: "${manifest.id}", executionId: eid, logs };
}
function notConfigured(start: number, eid: string, logs: ConnectorLog[], op: string): ConnectorResult {
  const d = Date.now() - start;
  logs.push(makeLog("warn", \`[\${op}] NOT_CONFIGURED\`));
  return { status: "NOT_CONFIGURED", success: false, error: "${manifest.name} credentials not configured.", duration: d, connectorId: "${manifest.id}", executionId: eid, logs };
}
function computeP95(arr: number[]): number {
  if (arr.length === 0) return 0;
  const s = [...arr].sort((a, b) => a - b);
  return s[Math.floor(s.length * 0.95)];
}

let _logSeq = 0;

// ── Connector ─────────────────────────────────────────────────────────────────

export class ${cls} implements IConnector, IProductionConnector {
  readonly id      = "${manifest.id}";
  readonly name    = "${manifest.name}";
  readonly version = "${manifest.version}";

  // ── Authentication state ─────────────────────────────────────────────────
${authCfg.stateBlock}
  private _initialized = false;
  private _lastValidation: ConnectorValidationResult | null = null;
  private _execHistory: ExecutionLogEntry[] = [];

  readonly internalMetrics = {
    totalRequests: 0, successRequests: 0, failedRequests: 0, deniedRequests: 0, retries: 0,
    latencyAllMs: [] as number[], avgLatencyMs: 0, p95LatencyMs: 0,
    uptimeStartMs: Date.now(), uptimeDurationMs: 0,
    perOperationMs: {} as Record<string, number[]>,
    operationCallCount: {} as Record<string, number>,
    totalExecutions: 0, authFailures: 0, invalidResponses: 0, externalFailures: 0,
  };

  // ── IConnector — metadata ────────────────────────────────────────────────

  metadata(): ConnectorMetadata {
    return {
      id:           this.id,
      name:         this.name,
      version:      this.version,
      description:  "${manifest.description}",
      author:       "${manifest.author}",
      capabilities: CAPABILITIES.map(c => c.id),
    };
  }

  async initialize(_ctx: ConnectorContext): Promise<void> {
    // TODO: initialise ${authCfg.tokenComment}
    this._initialized = false; // set true after successful auth check
  }

  async shutdown(): Promise<void> {
    this._initialized = false;
${authCfg.shutdownBlock}  }

  // ── IProductionConnector — Authentication ────────────────────────────────

  async connect(): Promise<AuthResult> {
    // TODO: obtain and validate credentials
    return { success: false, principal: null, error: "connect() not yet implemented" };
  }

  async disconnect(): Promise<void> {
    this._initialized = false;
${authCfg.shutdownBlock}  }

  async isAuthenticated(): Promise<boolean> {
    // TODO: verify credentials are valid
    return false;
  }

  async refreshAuthentication(): Promise<AuthResult> {
    return this.connect();
  }

  async permissions(): Promise<ConnectorPermissions> {
    const authed = await this.isAuthenticated();
    return {
      connectorId:       this.id,
      authenticated:     authed,
      principal:         null, // TODO: fill principal
      scopes:            authed ? [${manifest.requiredPermissions.map(p => `"${p}"`).join(", ")}] : [],
      missingRequired:   authed ? [] : ["credentials"],
      recommendations:   authed ? [] : ["Configure ${manifest.authType} credentials"],
      diagnostic:        authed ? "Authenticated" : "Not authenticated",
    };
  }

  async authenticationDiagnostics(): Promise<AuthenticationDiagnostics> {
    const authed = await this.isAuthenticated();
    return {
      configured:       ${authCfg.configuredCheck},
      authenticated:    authed,
      principal:        null, // TODO: fill principal
      tokenType:        "${manifest.authType}",
      expiryDetected:   false,
      scopesDeclared:   [${manifest.requiredPermissions.map(p => `"${p}"`).join(", ")}],
      issues:           authed ? [] : ["Not authenticated"],
    };
  }

  // ── IProductionConnector — Health ────────────────────────────────────────

  async health(): Promise<ConnectorHealthReport> {
    // TODO: implement real health checks
    const authed = await this.isAuthenticated();
    return {
      status:     authed ? "healthy" : "not_configured",
      connectorId: this.id,
      checkedAt:  Date.now(),
      details:    authed ? "Authenticated" : "Not configured",
      checks: [
        { name: "Authentication", passed: authed, detail: authed ? "OK" : "Not authenticated" },
      ],
    } as any;
  }

  async fullHealth(): Promise<ConnectorHealth> {
    const r = await this.health() as any;
    return { status: r.status, connectorId: r.connectorId, checkedAt: r.checkedAt, checks: r.checks ?? [], overallLatencyMs: 0, details: r.details };
  }

  async availability(): Promise<ConnectorAvailability> {
    const h = await this.health();
    return { available: h.status === "healthy", uptimeMs: this.internalMetrics.uptimeDurationMs, lastCheck: Date.now(), status: h.status as any };
  }

  async latency(): Promise<ConnectorLatency> {
    const all = this.internalMetrics.latencyAllMs;
    const min = all.length > 0 ? Math.min(...all) : 0;
    const max = all.length > 0 ? Math.max(...all) : 0;
    return { avgMs: this.internalMetrics.avgLatencyMs, p95Ms: this.internalMetrics.p95LatencyMs, minMs: min, maxMs: max, samples: all.length };
  }

  // ── IProductionConnector — Metrics ───────────────────────────────────────

  metrics(): ConnectorMetrics {
    const all = this.internalMetrics.latencyAllMs;
    return {
      connectorId:        this.id,
      totalRequests:      this.internalMetrics.totalRequests,
      successRequests:    this.internalMetrics.successRequests,
      failedRequests:     this.internalMetrics.failedRequests,
      deniedRequests:     this.internalMetrics.deniedRequests,
      retries:            this.internalMetrics.retries,
      latency: { avgMs: this.internalMetrics.avgLatencyMs, p95Ms: this.internalMetrics.p95LatencyMs, minMs: all.length > 0 ? Math.min(...all) : 0, maxMs: all.length > 0 ? Math.max(...all) : 0, samples: all.length },
      rateLimitRemaining: null,
      rateLimitLimit:     null,
      rateLimitUsagePct:  null,
      uptimeDurationMs:   this.internalMetrics.uptimeDurationMs,
      perOperation:       this.internalMetrics.operationCallCount,
    };
  }

  resetMetrics(): void {
    this.internalMetrics.totalRequests      = 0;
    this.internalMetrics.successRequests    = 0;
    this.internalMetrics.failedRequests     = 0;
    this.internalMetrics.deniedRequests     = 0;
    this.internalMetrics.retries            = 0;
    this.internalMetrics.latencyAllMs       = [];
    this.internalMetrics.avgLatencyMs       = 0;
    this.internalMetrics.p95LatencyMs       = 0;
    this.internalMetrics.operationCallCount = {};
    this.internalMetrics.perOperationMs     = {};
    this.internalMetrics.totalExecutions    = 0;
    this.internalMetrics.authFailures       = 0;
  }

  // ── IProductionConnector — Logging ───────────────────────────────────────

  logExecution(operationId: string, durationMs: number, success: boolean, detail = ""): void {
    this._execHistory.push({ id: \`${manifest.id}_\${Date.now()}_\${(++_logSeq).toString(36)}\`, operationId, timestamp: Date.now(), durationMs, success, detail });
    if (this._execHistory.length > 200) this._execHistory.splice(0, this._execHistory.length - 200);
  }

  executionHistory(limit = 50): ExecutionLogEntry[] {
    return this._execHistory.slice(-Math.min(limit, 200));
  }

  // ── IProductionConnector — Diagnostics ──────────────────────────────────

  async diagnostics(): Promise<ConnectorDiagnostics> {
    const authed = await this.isAuthenticated();
    const m      = this.internalMetrics;
    const e = (key: string, value: string, status: DiagnosticEntry["status"]): DiagnosticEntry => ({ key, value, status });
    return {
      connectorId:    this.id,
      generatedAt:    Date.now(),
      authentication: [
        e("configured",    ${authCfg.configuredCheck} ? "yes" : "no", ${authCfg.configuredCheck} ? "ok" : "error"),
        e("authenticated", String(authed),                             authed ? "ok" : "warning"),
      ],
      health: [
        e("initialized", String(this._initialized), this._initialized ? "ok" : "warning"),
      ],
      metrics: [
        e("totalRequests", String(m.totalRequests), "info"),
        e("avgLatencyMs",  String(m.avgLatencyMs),  m.avgLatencyMs < 500 ? "ok" : "warning"),
      ],
      capabilities: [
        e("count", String(CAPABILITIES.length), CAPABILITIES.length > 0 ? "ok" : "error"),
      ],
      errors:  [],
      summary: \`${manifest.name} — \${authed ? "authenticated" : "not configured"} · \${m.totalRequests} requests · \${CAPABILITIES.length} capabilities\`,
    };
  }

  // ── IProductionConnector — Policy ────────────────────────────────────────

  supportedCapabilities(): ConnectorCapability[] { return CAPABILITIES; }

  async authorization(operation: string): Promise<AuthorizationResult> {
    const cap = CAPABILITIES.find(c => c.id === operation);
    if (!cap) return { authorized: false, reason: \`Unknown operation: \${operation}\`, policyEvaluated: true };
    if (cap.requiredAuth && !(await this.isAuthenticated()))
      return { authorized: false, reason: "Authentication required", policyEvaluated: true };
    return { authorized: true, reason: "Authorized", policyEvaluated: true };
  }

  // ── IProductionConnector — Validation ───────────────────────────────────

  validate(): boolean { return true; }

  async validateAsync(): Promise<ConnectorValidationResult> {
    const checks: ConnectorValidationResult["checks"] = [];
    const authed = await this.isAuthenticated();
    checks.push({ name: "Authentication", passed: authed, detail: authed ? "Authenticated" : "Not authenticated" });
    const required = ["connectivity.ping"];
    const declared = this.metadata().capabilities;
    const missing  = required.filter(c => !declared.includes(c));
    checks.push({ name: "Required capabilities", passed: missing.length === 0, detail: missing.length === 0 ? "All required capabilities present" : \`Missing: \${missing.join(", ")}\` });
    const valid  = checks.every(c => c.passed);
    const result = { valid, checks, summary: valid ? "All checks passed" : \`\${checks.filter(c => c.passed).length}/\${checks.length} passed\` };
    this._lastValidation = result;
    return result;
  }

  async validateProduction(): Promise<ConnectorValidation> {
    const validator = new ProductionComplianceValidator();
    return validator.validate(this);
  }

  getLastValidation(): ConnectorValidationResult | null { return this._lastValidation; }

  // ── IProductionConnector — Certification ────────────────────────────────

  certificationStatus(): ConnectorCertification {
    return {
      level:       "LEVEL_1",
      label:       CERTIFICATION_LABELS["LEVEL_1"],
      certifiedAt: this.internalMetrics.uptimeStartMs,
      certifiedBy: "MemoryOS Connector SDK v1.0",
      validUntil:  null,
      notes:       ["Generated by MemoryOS Connector SDK v1.0", "Implement operations to advance certification level"],
    };
  }

  // ── IConnector — Execute ─────────────────────────────────────────────────

  async execute(operation: string, payload: Record<string, unknown>, context: ConnectorContext): Promise<ConnectorResult> {
    const start = Date.now();
    const eid   = context.executionId ?? makeExecutionId();
    const logs: ConnectorLog[] = [makeLog("info", \`[\${operation}] executionId=\${eid} Starting\`)];

    this.internalMetrics.totalRequests++;
    this.internalMetrics.totalExecutions++;
    this.internalMetrics.operationCallCount[operation] = (this.internalMetrics.operationCallCount[operation] ?? 0) + 1;

    try {
      const result = await this._dispatch(operation, payload, start, eid, logs);
      const ms = result.duration;
      if (!this.internalMetrics.perOperationMs[operation]) this.internalMetrics.perOperationMs[operation] = [];
      this.internalMetrics.perOperationMs[operation].push(ms);
      this.internalMetrics.latencyAllMs.push(ms);
      if (result.success) this.internalMetrics.successRequests++;
      else if (result.status === "NOT_CONFIGURED") this.internalMetrics.deniedRequests++;
      else this.internalMetrics.failedRequests++;
      const all = this.internalMetrics.latencyAllMs;
      this.internalMetrics.avgLatencyMs  = all.length > 0 ? Math.round(all.reduce((s, v) => s + v, 0) / all.length) : 0;
      this.internalMetrics.p95LatencyMs  = computeP95(all);
      this.internalMetrics.uptimeDurationMs = Date.now() - this.internalMetrics.uptimeStartMs;
      this.logExecution(operation, ms, result.success, result.success ? "" : result.error ?? "");
      return result;
    } catch (err) {
      this.internalMetrics.externalFailures++;
      this.internalMetrics.failedRequests++;
      const msg = err instanceof Error ? err.message : String(err);
      this.logExecution(operation, Date.now() - start, false, \`Exception: \${msg}\`);
      return fail(\`Unhandled exception: \${msg}\`, "internal", start, eid, logs, operation);
    }
  }

  // ── Private — dispatch ───────────────────────────────────────────────────

  private async _dispatch(
    operation: string, payload: Record<string, unknown>,
    start: number, eid: string, logs: ConnectorLog[],
  ): Promise<ConnectorResult> {

    // Not configured guard — replace with your credential check
    const configured = ${authCfg.configuredCheck};
    if (!configured) {
      this.internalMetrics.deniedRequests++;
      return notConfigured(start, eid, logs, operation);
    }

    switch (operation) {

      case "connectivity.ping":
        return ok({ pong: true, authenticated: await this.isAuthenticated(), timestamp: Date.now() }, start, eid, logs, operation);

${cases}

      default:
        return fail(\`Unknown operation: "\${operation}"\`, "internal", start, eid, logs, operation);
    }
  }
}
`;
  }

  /** Generate test file for the connector. */
  generateTests(manifest: ConnectorManifest): string {
    const cls = className(manifest.id);
    return `/**
 * ${manifest.id}Tests.ts — ${manifest.name} Test Suite
 * Generated by MemoryOS Connector SDK v1.0 · Beta-03
 */

import { ${cls} } from "./${cls}";
import { ProductionComplianceValidator } from "@/lib/production-connector-standard/ProductionComplianceValidator";
import { PCSGenerator } from "@/lib/production-connector-standard/PCSGenerator";

export interface ${cls}TestResult {
  id: string; name: string; category: string;
  status: "PASS" | "FAIL" | "SKIP"; durationMs: number; detail: string;
}
export interface ${cls}TestReport {
  results: ${cls}TestResult[]; passed: number; failed: number; total: number;
  overallStatus: "PASS" | "FAIL"; generatedAt: number; durationMs: number;
}

async function run(id: string, name: string, cat: string, fn: () => Promise<{status:"PASS"|"FAIL"|"SKIP"; detail:string}>): Promise<${cls}TestResult> {
  const t0 = Date.now();
  try { const r = await fn(); return { id, name, category: cat, status: r.status, durationMs: Date.now()-t0, detail: r.detail }; }
  catch (err) { return { id, name, category: cat, status: "FAIL", durationMs: Date.now()-t0, detail: \`Exception: \${err instanceof Error ? err.message : String(err)}\` }; }
}

export async function run${cls}Tests(): Promise<${cls}TestReport> {
  const t0 = Date.now();
  const c   = new ${cls}();
  const ctx = { executionId: \`test_\${Date.now()}\`, userId: "test", policyContext: {} };
  await c.initialize(ctx as any);
  const results: ${cls}TestResult[] = [];

  // IProductionConnector surface
  results.push(await run("01", "connect() present",               "Interface", async () => typeof c.connect === "function"               ? {status:"PASS",detail:"connect() implemented"}               : {status:"FAIL",detail:"connect() missing"}));
  results.push(await run("02", "disconnect() present",            "Interface", async () => typeof c.disconnect === "function"            ? {status:"PASS",detail:"disconnect() implemented"}            : {status:"FAIL",detail:"disconnect() missing"}));
  results.push(await run("03", "isAuthenticated() returns bool",  "Interface", async () => { const r = await c.isAuthenticated(); return typeof r === "boolean" ? {status:"PASS",detail:\`isAuthenticated()=\${r}\`} : {status:"FAIL",detail:"not boolean"}; }));
  results.push(await run("04", "permissions() returns object",    "Interface", async () => { const p = await c.permissions(); return p.connectorId ? {status:"PASS",detail:\`connectorId=\${p.connectorId}\`} : {status:"FAIL",detail:"missing connectorId"}; }));
  results.push(await run("05", "metrics() returns object",        "Interface", async () => { const m = c.metrics(); return typeof m.totalRequests === "number" ? {status:"PASS",detail:\`totalRequests=\${m.totalRequests}\`} : {status:"FAIL",detail:"missing totalRequests"}; }));
  results.push(await run("06", "diagnostics() returns object",    "Interface", async () => { const d = await c.diagnostics(); return d.connectorId ? {status:"PASS",detail:d.summary} : {status:"FAIL",detail:"missing connectorId"}; }));
  results.push(await run("07", "supportedCapabilities() returns array", "Interface", async () => { const caps = c.supportedCapabilities(); return Array.isArray(caps) && caps.length > 0 ? {status:"PASS",detail:\`\${caps.length} capabilities\`} : {status:"FAIL",detail:"empty or invalid"}; }));
  results.push(await run("08", "certificationStatus() returns object", "Interface", async () => { const cs = c.certificationStatus(); return cs.level ? {status:"PASS",detail:\`level=\${cs.level}\`} : {status:"FAIL",detail:"missing level"}; }));
  results.push(await run("09", "validateProduction() returns ConnectorValidation", "PCS", async () => { const v = await c.validateProduction(); return typeof v.score === "number" ? {status:"PASS",detail:\`score=\${(v.score*100).toFixed(0)}%\`} : {status:"FAIL",detail:"invalid shape"}; }));
  results.push(await run("10", "connectivity.ping operation", "Operations", async () => { const r = await c.execute("connectivity.ping", {}, ctx as any); return r.status !== undefined ? {status:"PASS",detail:\`status=\${r.status}\`} : {status:"FAIL",detail:"no status"}; }));
  results.push(await run("11", "PCSGenerator produces spec", "PCS", async () => { const spec = await new PCSGenerator().generate(c); return spec.connectorId === "${manifest.id}" ? {status:"PASS",detail:\`certLevel=\${spec.certificationLevel}\`} : {status:"FAIL",detail:"wrong connectorId"}; }));
  results.push(await run("12", "metrics tracked after execution", "Metrics", async () => { await c.execute("connectivity.ping", {}, ctx as any); const m = c.internalMetrics; return m.totalRequests > 0 ? {status:"PASS",detail:\`totalRequests=\${m.totalRequests} avg=\${m.avgLatencyMs}ms\`} : {status:"FAIL",detail:"metrics not tracked"}; }));

  const passed = results.filter(r => r.status === "PASS").length;
  const failed = results.filter(r => r.status === "FAIL").length;
  return { results, passed, failed, total: results.length, overallStatus: failed === 0 ? "PASS" : "FAIL", generatedAt: Date.now(), durationMs: Date.now() - t0 };
}
`;
  }

  /** Generate Knowledge Provider skeleton if requested. */
  generateKnowledgeProvider(manifest: ConnectorManifest): string {
    const cls = className(manifest.id);
    return `/**
 * ${cls}KnowledgeProvider.ts — ${manifest.name} Knowledge Provider
 * Generated by MemoryOS Connector SDK v1.0 · Beta-03
 *
 * GENERATED SKELETON — Implement fetchItems(), extractKnowledge(), buildTimeline().
 * No business logic included — structure only.
 */

import type { IKnowledgeSource } from "@/lib/knowledge-reconstruction/IKnowledgeSource";

export class ${cls}KnowledgeProvider implements IKnowledgeSource {
  readonly id          = "${manifest.id}-kp";
  readonly name        = "${manifest.name} Knowledge Provider";
  readonly description = "Knowledge extraction from ${manifest.provider}";
  readonly version     = "${manifest.version}";

  async isAvailable(): Promise<boolean> {
    // TODO: check if connector is authenticated
    return false;
  }

  async fetchKnowledge(_projectId: string): Promise<unknown[]> {
    // TODO: fetch items from ${manifest.provider}
    // Return array of raw provider records
    return [];
  }

  async extractEntities(_items: unknown[]): Promise<unknown[]> {
    // TODO: extract named entities (people, orgs, dates, etc.)
    return [];
  }

  async extractTimeline(_items: unknown[]): Promise<unknown[]> {
    // TODO: build chronological event list
    return [];
  }

  async buildProvenance(itemId: string): Promise<{ source: string; itemId: string; fetchedAt: number }> {
    return { source: this.id, itemId, fetchedAt: Date.now() };
  }
}
`;
  }

  private _authConfig(manifest: ConnectorManifest): {
    stateBlock: string; shutdownBlock: string; tokenComment: string; configuredCheck: string;
  } {
    switch (manifest.authType) {
      case "api_key":
      case "bearer":
        return {
          stateBlock: `  private _token: string | null = null;\n`,
          shutdownBlock: `    this._token = null;\n`,
          tokenComment: "token from env or SecretStore",
          configuredCheck: "!!this._token",
        };
      case "oauth2":
        return {
          stateBlock: `  private _accessToken: string | null = null;\n  private _refreshToken: string | null = null;\n`,
          shutdownBlock: `    this._accessToken = null;\n    this._refreshToken = null;\n`,
          tokenComment: "OAuth2 access token",
          configuredCheck: "!!this._accessToken",
        };
      case "basic":
        return {
          stateBlock: `  private _credentials: { username: string; password: string } | null = null;\n`,
          shutdownBlock: `    this._credentials = null;\n`,
          tokenComment: "Basic Auth credentials",
          configuredCheck: "!!this._credentials",
        };
      case "session":
        return {
          stateBlock: ``,
          shutdownBlock: ``,
          tokenComment: "session (always available in-platform)",
          configuredCheck: "true",
        };
      default: // "none"
        return {
          stateBlock: ``,
          shutdownBlock: ``,
          tokenComment: "no authentication required",
          configuredCheck: "true",
        };
    }
  }
}