/**
 * DocumentationGenerator.ts — MemoryOS Connector SDK v1.0
 * Beta-03 · 2026-07-13
 *
 * Generates README, Connector Guide, PCS Compliance Guide,
 * Manifest Guide, Certification Guide, and Knowledge Provider Guide.
 */

import type { ConnectorManifest } from "./SDKTypes";

function className(id: string) {
  return id.split(/[-_]/).map(s => s.charAt(0).toUpperCase() + s.slice(1)).join("") + "Connector";
}

export class DocumentationGenerator {

  generateReadme(manifest: ConnectorManifest): string {
    const cls = className(manifest.id);
    return `# ${manifest.name}

> Generated by **MemoryOS Connector SDK v1.0** · Provider: ${manifest.provider} · Auth: ${manifest.authType} · PCS v1.0

## Overview

${manifest.description}

- **Connector ID:** \`${manifest.id}\`
- **Version:** \`${manifest.version}\`
- **Auth Type:** \`${manifest.authType}\`
- **Production Level:** \`${manifest.productionLevel}\`
- **PCS Version:** \`${manifest.compatibility.pcsVersion}\`

## Capabilities

| ID | Type | Auth Required | Read Only |
|----|------|--------------|-----------|
${manifest.capabilities.map(c => `| \`${c.id}\` | ${c.type} | ${c.requiredAuth} | ${c.readOnly} |`).join("\n")}

## Quick Start

\`\`\`typescript
import { ${cls} } from "./${cls}";

const connector = new ${cls}();
await connector.initialize(context);

// Run any operation
const result = await connector.execute("connectivity.ping", {}, context);
console.log(result.status); // "SUCCESS" | "FAILED" | "NOT_CONFIGURED"
\`\`\`

## Certification

Run the included test suite to validate PCS compliance:

\`\`\`typescript
import { run${cls}Tests } from "./${manifest.id}Tests";
const report = await run${cls}Tests();
console.log(report.overallStatus); // "PASS" | "FAIL"
\`\`\`

## Required Permissions

${manifest.requiredPermissions.length > 0
  ? manifest.requiredPermissions.map(p => `- \`${p}\``).join("\n")
  : "No special permissions required."}

## Architecture

This connector was generated by MemoryOS Connector SDK v1.0 and fully implements:

- \`IProductionConnector\` — all 20+ mandatory methods
- \`IConnector\` — lifecycle and execute()
- Production Connector Standard (PCS) v1.0
${manifest.hasKnowledgeProvider ? "- `IKnowledgeSource` — Knowledge Provider skeleton included\n" : ""}
---
*Generated ${new Date().toISOString().split("T")[0]} · MemoryOS Connector SDK v1.0*
`;
  }

  generatePCSGuide(manifest: ConnectorManifest): string {
    return `# PCS Compliance Guide — ${manifest.name}

## What is PCS?

The **Production Connector Standard (PCS) v1.0** defines the mandatory interface every
MemoryOS production connector must implement. It is provider-agnostic.

## Compliance Checklist

### Required Methods (from IProductionConnector)

| Method | Status |
|--------|--------|
| \`connect()\` | Generated ✓ — implement credentials |
| \`disconnect()\` | Generated ✓ |
| \`isAuthenticated()\` | Generated ✓ — implement check |
| \`refreshAuthentication()\` | Generated ✓ |
| \`permissions()\` | Generated ✓ — fill principal |
| \`authenticationDiagnostics()\` | Generated ✓ |
| \`health()\` | Generated ✓ — add real checks |
| \`fullHealth()\` | Generated ✓ |
| \`availability()\` | Generated ✓ |
| \`latency()\` | Generated ✓ |
| \`metrics()\` | Generated ✓ — automatic tracking |
| \`resetMetrics()\` | Generated ✓ |
| \`logExecution()\` | Generated ✓ — automatic |
| \`executionHistory()\` | Generated ✓ |
| \`diagnostics()\` | Generated ✓ — extend with provider info |
| \`supportedCapabilities()\` | Generated ✓ |
| \`authorization()\` | Generated ✓ |
| \`validate()\` | Generated ✓ |
| \`validateProduction()\` | Generated ✓ — uses ProductionComplianceValidator |
| \`certificationStatus()\` | Generated ✓ |

### To reach LEVEL_3 (Production)

1. Implement \`connect()\` with real credential validation
2. Implement all operations in \`_dispatch()\`
3. Add real health checks beyond \`connectivity.ping\`
4. Pass \`ProductionComplianceValidator\` with score >= 70%

### To reach LEVEL_4 (Certified)

1. All LEVEL_3 requirements
2. Compliance score >= 90%
3. All required PCS checks pass
4. No critical technical debt

## Running Validation

\`\`\`typescript
const v = await connector.validateProduction();
console.log(v.score, v.overall);
\`\`\`
`;
  }

  generateManifestGuide(manifest: ConnectorManifest): string {
    return `# Connector Manifest Guide — ${manifest.name}

## Manifest Fields

\`\`\`json
{
  "specVersion": "${manifest.specVersion}",
  "id": "${manifest.id}",
  "name": "${manifest.name}",
  "provider": "${manifest.provider}",
  "version": "${manifest.version}",
  "authType": "${manifest.authType}",
  "productionLevel": "${manifest.productionLevel}",
  "capabilities": [ /* ${manifest.capabilities.length} capability(ies) */ ]
}
\`\`\`

## Auth Type Reference

| Type | Description |
|------|-------------|
| \`api_key\` | Static API key or PAT — stored in environment |
| \`oauth2\` | OAuth 2.0 authorization code flow |
| \`session\` | Platform-managed session (e.g. Base44) |
| \`bearer\` | Bearer token in Authorization header |
| \`basic\` | HTTP Basic username/password |
| \`none\` | No authentication required |

## Capability Types

| Type | Usage |
|------|-------|
| READ | Fetch a single resource by ID |
| LIST | Paginated list of resources |
| SEARCH | Query/filter resources |
| WRITE | Create a new resource |
| UPDATE | Modify an existing resource |
| DELETE | Remove a resource |
| SYNC | Full or incremental sync |
| EVENT | Subscribe to webhook events |
| STREAM | Streaming data (SSE, WS) |
| CUSTOM | Provider-specific operation |
`;
  }

  generateCertificationGuide(manifest: ConnectorManifest): string {
    return `# Certification Guide — ${manifest.name}

## Certification Levels

| Level | Label | Requirement |
|-------|-------|-------------|
| LEVEL_0 | Experimental | Generated — no operations implemented |
| LEVEL_1 | Development | Basic structure, some ops implemented |
| LEVEL_2 | Beta | Core ops working, health checks passing |
| LEVEL_3 | Production | All ops, PCS score >= 70%, no critical debt |
| LEVEL_4 | Certified | PCS score >= 90%, reference quality |

## Current Level: LEVEL_1 (Development)

This connector was just generated. Implement operations to advance.

## Steps to LEVEL_3

1. Implement \`connect()\` and \`isAuthenticated()\`
2. Implement all \`_dispatch()\` cases for your capabilities
3. Add real health checks in \`health()\`
4. Run the test suite: \`run${className(manifest.id)}Tests()\`
5. Run PCS validation: \`connector.validateProduction()\`
6. Fix all FAIL and WARNING results

## Generating a Certification Report

\`\`\`typescript
import { PCSGenerator } from "@/lib/production-connector-standard/PCSGenerator";
const spec = await new PCSGenerator().generate(connector);
console.log(spec.certificationLevel, spec.complianceScore);
\`\`\`
`;
  }

  generateKnowledgeProviderGuide(manifest: ConnectorManifest): string {
    return `# Knowledge Provider Guide — ${manifest.name}

## What is a Knowledge Provider?

A Knowledge Provider extracts structured knowledge from a data source and makes
it available to the MemoryOS Knowledge Reconstruction Engine (KRE).

## Skeleton Generated

The file \`${className(manifest.id)}KnowledgeProvider.ts\` was generated with:

- \`fetchKnowledge(projectId)\` — fetch raw items from ${manifest.provider}
- \`extractEntities(items)\` — extract named entities
- \`extractTimeline(items)\` — build chronological timeline
- \`buildProvenance(itemId)\` — record data lineage

## Implementation Steps

1. In \`fetchKnowledge()\`: call your connector's LIST operations
2. In \`extractEntities()\`: map provider records to MemoryOS entity types
3. In \`extractTimeline()\`: sort events by date and map to TimelineEvent format
4. Register in \`KnowledgeReconstructionEngine\`

## Provenance

Always populate provenance for audit trails:
\`\`\`typescript
{ source: "${manifest.id}-kp", itemId: "record_id", fetchedAt: Date.now() }
\`\`\`
`;
  }
}