/**
 * UCRTypes.ts — Engineering Sprint E-02.4
 * Canonical types for the Universal Connector Router.
 *
 * SRP: apenas contratos de dados. Sem lógica. Sem rede. Sem OAuth.
 *
 * Consumers:
 *   - IConnector
 *   - ConnectorRegistry
 *   - UniversalConnectorRouter
 *   - ConnectorCapabilityExecutor (adapts to ICapabilityExecutor)
 */

// ── ConnectorCapability ───────────────────────────────────────────────────────

export interface ConnectorCapability {
  readonly id:                     string;
  readonly version:                string;
  readonly description:            string;
  readonly requiresAuthentication: boolean;
  readonly requiresConfirmation:   boolean;
  readonly supportsStreaming:       boolean;
  readonly estimatedCostMs:        number;
  readonly timeoutMs:              number;
  readonly metadata:               Readonly<Record<string, unknown>>;
}

// ── ConnectorInput / ConnectorResult ─────────────────────────────────────────

// B-04: ConnectorExecutionContext imported from RuntimeTypes to avoid duplication.
// We re-export a minimal shape here so UCRTypes stays self-contained for
// consumers that don't import RuntimeTypes directly.
export interface ConnectorCallerContext {
  readonly userId:       string;
  readonly workspaceId:  string;
  readonly sessionId:    string;
  readonly goalId?:      string;
  readonly requestId?:   string;
  readonly origin?:      string;
}

export interface ConnectorInput {
  readonly executionId:  string;
  readonly capability:   string;
  readonly parameters:   Readonly<Record<string, unknown>>;
  /** B-04: real caller context forwarded from RuntimeExecutionContext.connectorCtx */
  readonly connectorCtx?: ConnectorCallerContext;
}

// C-01: Full status vocabulary — all states from the runtime connector are preserved.
// "not_found" maps from NOT_CONFIGURED/NOT_SUPPORTED (connector exists but not usable).
// "denied" preserved as explicit state — not collapsed into "failed".
export type ConnectorResultStatus =
  | "success"
  | "failed"
  | "timeout"
  | "not_found"
  | "denied";       // C-05: NOT_CONFIGURED / NOT_SUPPORTED must not collapse to "failed"

// C-02/C-04: Full contract — executionId, connectorId, logs preserved end-to-end.
export interface ConnectorResult {
  readonly connectorId:  string;
  readonly capability:   string;
  readonly status:       ConnectorResultStatus;
  readonly output:       unknown;
  readonly error:        string | null;
  readonly durationMs:   number;
  // C-04: propagated from runtime connector — never generated by bridge or router
  readonly executionId:  string;
  // C-04: connector logs — preserved for observability; never discarded
  readonly logs:         readonly ConnectorLog[];
}

// C-04: ConnectorLog preserved from runtime through the entire chain.
export interface ConnectorLog {
  readonly timestamp: number;
  readonly level:     "info" | "warn" | "error";
  readonly message:   string;
}

// ── IConnector ────────────────────────────────────────────────────────────────

export interface IConnector {
  /** Unique, stable identifier (e.g. "gmail", "calendar", "drive", "github"). */
  connectorId(): string;

  /** Declares all capabilities this connector supports. */
  capabilities(): readonly ConnectorCapability[];

  /** Executes a capability. Must never throw — return a failed result instead. */
  execute(input: ConnectorInput): Promise<ConnectorResult>;

  /** Returns basic health information. */
  health(): ConnectorHealth;

  /** Returns human-readable metadata about this connector. */
  metadata(): ConnectorMetadata;
}

// ── Health / Metadata ─────────────────────────────────────────────────────────

export type ConnectorHealthStatus = "healthy" | "degraded" | "unavailable";

export interface ConnectorHealth {
  readonly status:     ConnectorHealthStatus;
  readonly message:    string;
  readonly checkedAt:  number;
}

export interface ConnectorMetadata {
  readonly name:        string;
  readonly version:     string;
  readonly description: string;
  readonly author:      string;
  readonly tags:        readonly string[];
}

// ── Router result ─────────────────────────────────────────────────────────────

export interface RouterResult {
  readonly found:         boolean;
  readonly connectorId:   string;
  readonly capability:    string;
  readonly result:        ConnectorResult | null;
  readonly error:         string | null;
  // C-05: when found=false, indicates whether the failure was "not_found" (registry miss)
  // vs. "not_configured" (connector present but denied). Populated by the router.
  readonly notFoundReason?: "connector_not_registered" | "capability_not_declared";
}