// engineering.image.create V1 — ONE supertool for NEW visual creation.
// Separation of concerns (official): engineering.image.create creates pixels/compositions
// that do not exist yet; engineering.image.edit edits/composes material that already exists.
// Generation reuses the PROVEN path: Cloudflare Workers AI REST -> @cf/black-forest-labs/
// flux-1-schnell -> valid image bytes. Composition delegates ALL document/layer/text/export
// work to engineering.image.edit (src/imageEdit.ts) over the EXISTING local relay — this
// tool never implements a second editor, bridge or protocol. Generated bytes are delivered
// to the local Windows executor over THIS server's HTTPS origin at /image-asset/<uuid>
// (short TTL) because the existing Photopea executor resolves sources as URLs or local
// paths only. Fail-closed everywhere. Credentials are resolved from env or an
// operator-provisioned credential file and are NEVER returned, logged or echoed. No raw
// shell/JS/JSON-RPC/toolName/script/URL execution exists anywhere in the schema.
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import type { IncomingMessage, ServerResponse } from "node:http";
import * as z from "zod/v4";
import { runImageEdit, type ImageEditInput } from "./imageEdit.ts";

export const IMAGE_ASSET_PATH_PREFIX = "/image-asset/";
const ASSET_TTL_MS = 15 * 60_000;
const GENERATION_TIMEOUT_MS = 90_000;
const DEFAULT_PROVIDER_MODEL = "@cf/black-forest-labs/flux-1-schnell";
const PROVIDER_RUN_URL = "https://api.cloudflare.com/client/v4/accounts/{account}/ai/run/{model}";

export class ImageCreateError extends Error {
  readonly code: string;
  constructor(code: string, message: string) {
    super(message);
    this.code = code;
    this.name = "ImageCreateError";
  }
}

// ---- short-TTL in-memory asset delivery (one random-UUID URL per generated image) ----
type AssetEntry = { bytes: Buffer; contentType: string; expiresAt: number };
const assetStore = new Map<string, AssetEntry>();
function sweepAssets(now: number): void {
  for (const [id, entry] of assetStore) if (entry.expiresAt <= now) assetStore.delete(id);
}
export function putGeneratedAsset(bytes: Buffer, contentType: string, now = Date.now()): string {
  sweepAssets(now);
  const id = randomUUID();
  assetStore.set(id, { bytes, contentType, expiresAt: now + ASSET_TTL_MS });
  return id;
}
export function imageAssetCount(now = Date.now()): number {
  sweepAssets(now);
  return assetStore.size;
}
export type AssetLookup = { handled: true; status: number; contentType?: string; bytes?: Buffer } | { handled: false };
export function serveImageAsset(method: string, url: string | undefined, now = Date.now()): AssetLookup {
  if (method !== "GET") return { handled: false };
  let pathname = "";
  try { pathname = new URL(url ?? "/", "http://localhost").pathname; } catch { return { handled: false }; }
  if (!pathname.startsWith(IMAGE_ASSET_PATH_PREFIX)) return { handled: false };
  const id = pathname.slice(IMAGE_ASSET_PATH_PREFIX.length);
  sweepAssets(now);
  const entry = id.length > 0 ? assetStore.get(id) : undefined;
  if (!entry) return { handled: true, status: 404 };
  return { handled: true, status: 200, contentType: entry.contentType, bytes: entry.bytes };
}
export function handleImageAssetRequest(request: IncomingMessage, response: ServerResponse): boolean {
  const lookup = serveImageAsset(request.method ?? "", request.url);
  if (!lookup.handled) return false;
  if (lookup.status === 200 && lookup.bytes) {
    response.writeHead(200, { "content-type": lookup.contentType ?? "application/octet-stream", "content-length": String(lookup.bytes.length), "cache-control": "no-store" });
    response.end(lookup.bytes);
    return true;
  }
  response.writeHead(404, { "content-type": "application/json" });
  response.end(JSON.stringify({ error: "ASSET_NOT_FOUND_OR_EXPIRED" }));
  return true;
}

// ---- credential resolution (fail-closed; values never logged, never returned in results) ----
export type ImageCreateCredential = { apiToken: string; accountId: string };
export function credentialFilePath(): string {
  return process.env.ENG_MCP_IMAGE_CREATE_CREDENTIAL_FILE ?? "/data/image-create.cloudflare.json";
}
export async function resolveGenerationCredential(overrides: { env?: NodeJS.ProcessEnv; file?: string } = {}): Promise<ImageCreateCredential | null> {
  const env = overrides.env ?? process.env;
  const envToken = env.CLOUDFLARE_API_TOKEN;
  const envAccount = env.CLOUDFLARE_ACCOUNT_ID;
  if (typeof envToken === "string" && envToken.length > 0 && typeof envAccount === "string" && envAccount.length > 0)
    return { apiToken: envToken, accountId: envAccount };
  try {
    const parsed = JSON.parse(await readFile(overrides.file ?? credentialFilePath(), "utf8")) as { apiToken?: unknown; accountId?: unknown };
    if (typeof parsed.apiToken === "string" && parsed.apiToken.length > 0 && typeof parsed.accountId === "string" && parsed.accountId.length > 0)
      return { apiToken: parsed.apiToken, accountId: parsed.accountId };
  } catch { /* missing or invalid credential file => fail-closed at call time */ }
  return null;
}

// ---- proven generation path: Cloudflare Workers AI REST (flux-1-schnell) ----
export type GenerationRequest = { prompt: string; width?: number; height?: number; model?: string };
export type GenerationResult = { bytes: Buffer; contentType: string; model: string };
export async function generateWithProvider(credential: ImageCreateCredential, request: GenerationRequest): Promise<GenerationResult> {
  const model = request.model ?? DEFAULT_PROVIDER_MODEL;
  const url = PROVIDER_RUN_URL.replace("{account}", encodeURIComponent(credential.accountId)).replace("{model}", encodeURIComponent(model));
  const payload: Record<string, unknown> = { prompt: request.prompt, steps: 4 };
  if (request.width !== undefined) payload.width = request.width;
  if (request.height !== undefined) payload.height = request.height;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), GENERATION_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { authorization: `Bearer ${credential.apiToken}`, "content-type": "application/json" },
      body: JSON.stringify(payload),
      signal: controller.signal
    });
    if (!res.ok) throw new ImageCreateError("GENERATION_FAILED", `generation provider rejected the request (HTTP ${res.status})`);
    const body = await res.json().catch(() => null) as { result?: { image?: unknown } } | null;
    const encoded = body?.result?.image;
    if (typeof encoded !== "string" || encoded.length < 100) throw new ImageCreateError("GENERATION_FAILED", "generation provider returned no usable image payload");
    const bytes = Buffer.from(encoded, "base64");
    if (bytes.length === 0) throw new ImageCreateError("GENERATION_FAILED", "generation provider image payload could not be decoded");
    return { bytes, contentType: "image/jpeg", model };
  } catch (error) {
    if (error instanceof ImageCreateError) throw error;
    throw new ImageCreateError("GENERATION_FAILED", `generation provider call failed: ${error instanceof Error ? error.message : "unknown failure"}`);
  } finally {
    clearTimeout(timer);
  }
}

// ---- strict structured schema: 7 high-level actions, no raw execution anywhere ----
const num = (min: number, max: number) => z.number().min(min).max(max);
const placement = z.object({
  position: z.object({ x: num(-20000, 20000), y: num(-20000, 20000) }).strict().optional(),
  width: num(1, 20000).optional(),
  height: num(1, 20000).optional(),
  scale: num(0.01, 50).optional()
}).strict();
const composeElement = z.object({
  type: z.enum(["generatedImage", "background", "product", "logo", "text", "shape"]),
  path: z.string().min(1).max(500).optional(),
  text: z.string().min(1).max(2000).optional(),
  font: z.string().max(120).optional(),
  fontSize: num(4, 2000).optional(),
  color: z.string().max(32).optional(),
  shape: z.enum(["rectangle", "ellipse"]).optional(),
  position: z.object({ x: num(-20000, 20000), y: num(-20000, 20000) }).strict().optional(),
  width: num(1, 20000).optional(),
  height: num(1, 20000).optional(),
  scale: num(0.01, 50).optional()
}).strict();

export const imageCreateInputSchema = z.object({
  action: z.enum(["generate", "background", "scene", "product", "campaign", "compose", "variation"]),
  prompt: z.string().min(1).max(2000).optional(),
  // Provider-safe generation bounds (256..1024, multiples of 8) are enforced at runtime so
  // the deterministic error is the tool's own INVALID_DIMENSIONS; schema bounds are looser.
  width: z.number().int().min(64).max(4096).optional(),
  height: z.number().int().min(64).max(4096).optional(),
  // Optional technical pin only. User intent is "create image"; the default is the proven
  // provider model and the schema never requires a provider/model name.
  model: z.literal("flux-1-schnell").optional(),
  count: z.number().int().min(1).max(4).optional(),
  styleHints: z.array(z.string().min(1).max(200)).max(4).optional(),
  outputPath: z.string().min(1).max(500).optional(),
  compose: z.boolean().optional(),
  // Accepted ONLY to fail closed: the provider has no image-reference mode in v1.
  referenceImages: z.array(z.string().min(1).max(500)).max(4).optional(),
  product: z.object({ path: z.string().min(1).max(500), placement: placement.optional() }).strict().optional(),
  logo: z.object({ path: z.string().min(1).max(500), placement: placement.optional() }).strict().optional(),
  canvas: z.object({ width: z.number().int().min(64).max(8000), height: z.number().int().min(64).max(8000) }).strict().optional(),
  concept: z.string().min(1).max(200).optional(),
  headline: z.string().min(1).max(120).optional(),
  subheadline: z.string().min(1).max(200).optional(),
  cta: z.string().min(1).max(80).optional(),
  elements: z.array(composeElement).min(1).max(12).optional()
}).strict();

export type ImageCreateInput = z.infer<typeof imageCreateInputSchema>;
type OutputFormat = "png" | "jpg" | "jpeg" | "webp";
const OUTPUT_FORMATS: readonly OutputFormat[] = ["png", "jpg", "jpeg", "webp"];
type ElementInput = NonNullable<ImageEditInput["elements"]>[number];
type ComposeElementInput = z.infer<typeof composeElement>;
type PlacementInput = z.infer<typeof placement>;

export type ImageCreateDeps = {
  credentialLoader?: () => Promise<ImageCreateCredential | null>;
  generate?: (request: GenerationRequest) => Promise<GenerationResult>;
  edit?: (input: ImageEditInput) => Promise<Record<string, unknown>>;
  putAsset?: (bytes: Buffer, contentType: string) => string;
  publicBaseUrl?: string;
};

const RELAY_CODES = new Set(["LOCAL_RELAY_DISABLED", "LOCAL_EDITOR_OFFLINE", "RELAY_TIMEOUT", "RELAY_INVALID_RESPONSE", "RELAY_DISCONNECTED"]);
type EditOutcome = { ok: true; result: Record<string, unknown> } | { ok: false; code: string; message: string };
async function editStep(deps: ImageCreateDeps, input: ImageEditInput, step: string): Promise<EditOutcome> {
  const edit = deps.edit ?? ((candidate: ImageEditInput) => runImageEdit(candidate));
  const result = await edit(input);
  if (result.status === "ok") return { ok: true, result };
  const code = typeof result.code === "string" ? result.code : "EXECUTOR_ERROR";
  const message = typeof result.message === "string" ? result.message : "executor rejected the request";
  return { ok: false, code, message: `${step}: ${code}: ${message}` };
}
function mapEditFailure(step: string, failure: { code: string; message: string }, assetPaths: string[] = []): ImageCreateError {
  if (RELAY_CODES.has(failure.code)) return new ImageCreateError(failure.code, failure.message);
  if (assetPaths.some((assetPath) => assetPath.length > 0 && failure.message.includes(assetPath))) return new ImageCreateError("INPUT_ASSET_NOT_FOUND", failure.message);
  if (step === "export") return new ImageCreateError("EXPORT_FAILED", failure.message);
  if (step.startsWith("open-input:") || step.startsWith("place-input:")) return new ImageCreateError("INPUT_ASSET_NOT_FOUND", failure.message);
  return new ImageCreateError("COMPOSITION_FAILED", failure.message);
}
function exportOf(result: Record<string, unknown>): Record<string, unknown> | null {
  const output = result.output;
  return typeof output === "object" && output !== null ? output as Record<string, unknown> : null;
}

function outputFormatOf(outputPath: string): OutputFormat | null {
  const match = /\.([a-z0-9]+)$/i.exec(outputPath.trim());
  if (!match) return null;
  const ext = match[1].toLowerCase();
  return (OUTPUT_FORMATS as readonly string[]).includes(ext) ? ext as OutputFormat : null;
}
function withOutputIndex(outputPath: string, index: number): string {
  const match = /^(.*?)(\.[a-z0-9]+)?$/i.exec(outputPath.trim());
  const stem = match && match[2] ? match[1] : outputPath.trim();
  const ext = match && match[2] ? match[2] : "";
  return `${stem}-${index}${ext || ".png"}`;
}
function providerBackgroundSize(canvas: { width: number; height: number }): { width: number; height: number } {
  const snap = (value: number) => Math.max(256, Math.min(1024, Math.round(value / 8) * 8));
  if (canvas.width >= 256 && canvas.width <= 1024 && canvas.height >= 256 && canvas.height <= 1024 && canvas.width % 8 === 0 && canvas.height % 8 === 0)
    return { width: canvas.width, height: canvas.height };
  const ratio = canvas.width / canvas.height;
  return ratio >= 1 ? { width: 1024, height: snap(1024 / ratio) } : { width: snap(1024 * ratio), height: 1024 };
}
function validateGenerationDimensions(input: ImageCreateInput): void {
  for (const [label, value] of [["width", input.width], ["height", input.height]] as const) {
    if (value === undefined) continue;
    if (value < 256 || value > 1024 || value % 8 !== 0)
      throw new ImageCreateError("INVALID_DIMENSIONS", `${label} must be 256..1024 and a multiple of 8 (generation provider bounds)`);
  }
}
function requirePrompt(input: ImageCreateInput): string {
  const prompt = input.prompt?.trim();
  if (!prompt) throw new ImageCreateError("INPUT_INVALID", `action ${input.action} requires prompt`);
  return prompt;
}
function requireOutput(input: ImageCreateInput, required: boolean): { path: string; format: OutputFormat } | null {
  const path = input.outputPath?.trim();
  if (!path) {
    if (required) throw new ImageCreateError("INPUT_INVALID", `action ${input.action} requires outputPath`);
    return null;
  }
  const format = outputFormatOf(path);
  if (!format) throw new ImageCreateError("INPUT_INVALID", `outputPath must end with one of: ${OUTPUT_FORMATS.join("/")}`);
  return { path, format };
}
function publicBaseUrl(deps: ImageCreateDeps): string {
  const raw = deps.publicBaseUrl ?? process.env.ENG_MCP_IMAGE_CREATE_PUBLIC_BASE_URL ?? "https://memoryos-engmcp.2-25-96-245.nip.io";
  return raw.replace(/\/+$/, "");
}

function mapComposeElement(element: ComposeElementInput, index: number): ElementInput {
  if (element.type === "text") {
    if (!element.text) throw new ImageCreateError("INPUT_INVALID", `elements[${index}]: text element requires text`);
    return {
      type: "text",
      text: element.text,
      ...(element.font ? { font: element.font } : {}),
      ...(element.fontSize !== undefined ? { fontSize: element.fontSize } : {}),
      ...(element.color ? { color: element.color } : {}),
      ...(element.position ? { position: element.position } : {})
    };
  }
  if (element.type === "shape") {
    if (!element.shape || !element.position || element.width === undefined || element.height === undefined)
      throw new ImageCreateError("INPUT_INVALID", `elements[${index}]: shape element requires shape, position, width and height`);
    return {
      type: "shape",
      shape: element.shape,
      position: element.position,
      width: element.width,
      height: element.height,
      ...(element.color ? { color: element.color } : {})
    };
  }
  if (!element.path) throw new ImageCreateError("INPUT_INVALID", `elements[${index}]: ${element.type} element requires path`);
  return {
    type: "image",
    path: element.path,
    ...(element.position ? { position: element.position } : {}),
    ...(element.width !== undefined ? { width: element.width } : {}),
    ...(element.height !== undefined ? { height: element.height } : {}),
    ...(element.scale !== undefined ? { scale: element.scale } : {})
  };
}
function productElement(product: { path: string; placement?: PlacementInput }, canvas: { width: number; height: number }): ElementInput {
  const width = product.placement?.width ?? Math.round(canvas.width * 0.5);
  const height = product.placement?.height ?? Math.round(canvas.height * 0.55);
  const position = product.placement?.position ?? { x: Math.round((canvas.width - width) / 2), y: Math.round(canvas.height * 0.24) };
  return {
    type: "image",
    path: product.path,
    position,
    width,
    height,
    ...(product.placement?.scale !== undefined ? { scale: product.placement.scale } : {})
  };
}
function logoElement(logo: { path: string; placement?: PlacementInput }, canvas: { width: number; height: number } | null): ElementInput {
  const width = logo.placement?.width ?? (canvas ? Math.round(canvas.width * 0.16) : undefined);
  const height = logo.placement?.height ?? (canvas ? Math.round(canvas.height * 0.09) : undefined);
  const position = logo.placement?.position ?? (canvas ? { x: Math.round(canvas.width * 0.05), y: Math.round(canvas.height * 0.045) } : { x: 32, y: 32 });
  return {
    type: "image",
    path: logo.path,
    position,
    ...(width !== undefined ? { width } : {}),
    ...(height !== undefined ? { height } : {}),
    ...(logo.placement?.scale !== undefined ? { scale: logo.placement.scale } : {})
  };
}
function textElement(text: string, canvas: { width: number; height: number }, yRatio: number, sizeRatio: number): ElementInput {
  return {
    type: "text",
    text,
    fontSize: Math.max(12, Math.round(canvas.height * sizeRatio)),
    color: "#ffffff",
    position: { x: Math.round(canvas.width * 0.06), y: Math.round(canvas.height * yRatio) }
  };
}

type RunContext = {
  outputs: Record<string, unknown>[];
  generatedAssets: Record<string, unknown>[];
  operationsApplied: string[];
  warnings: string[];
  document: Record<string, unknown> | null;
};
async function generateAndStage(plan: GenerationPlan, deps: ImageCreateDeps, ctx: RunContext): Promise<string> {
  let generation: GenerationResult;
  if (deps.generate) {
    generation = await deps.generate({ prompt: plan.prompt, width: plan.width, height: plan.height, model: plan.model });
  } else {
    const credential = await (deps.credentialLoader ?? resolveGenerationCredential)();
    if (!credential)
      throw new ImageCreateError("GENERATION_PROVIDER_UNAVAILABLE", "no generation credential available (env CLOUDFLARE_API_TOKEN/CLOUDFLARE_ACCOUNT_ID or operator-provisioned credential file); failing closed");
    generation = await generateWithProvider(credential, { prompt: plan.prompt, width: plan.width, height: plan.height, model: plan.model });
  }
  const putAsset = deps.putAsset ?? putGeneratedAsset;
  const assetId = putAsset(generation.bytes, generation.contentType);
  ctx.generatedAssets.push({ index: ctx.generatedAssets.length + 1, contentType: generation.contentType, bytes: generation.bytes.length, provider: "cloudflare-workers-ai", model: generation.model });
  ctx.operationsApplied.push(`generate:${generation.model}`);
  return `${publicBaseUrl(deps)}${IMAGE_ASSET_PATH_PREFIX}${assetId}`;
}
type GenerationPlan = { prompt: string; width?: number; height?: number; model?: string };
async function generateDeliverExport(plan: GenerationPlan, output: { path: string; format: OutputFormat }, composeForEditing: boolean, deps: ImageCreateDeps, ctx: RunContext): Promise<Record<string, unknown>> {
  const assetUrl = await generateAndStage(plan, deps, ctx);
  const opened = await editStep(deps, { action: "document", document: { op: "open", path: assetUrl } }, "open-generated");
  if (!opened.ok) throw mapEditFailure("open-generated", opened);
  ctx.operationsApplied.push("open:generated-asset");
  ctx.document = { opened: true, source: "generated", composedForEditing: composeForEditing };
  const exported = await editStep(deps, { action: "export", output: { path: output.path, format: output.format, overwrite: true } }, "export");
  if (!exported.ok) throw mapEditFailure("export", exported);
  ctx.operationsApplied.push(`export:${output.format}`);
  return exported.result;
}
type Finish = (status: "ok" | "partial" | "error", extra?: Record<string, unknown>) => Record<string, unknown>;

async function runGenerationFamily(input: ImageCreateInput, deps: ImageCreateDeps, ctx: RunContext, finish: Finish): Promise<Record<string, unknown>> {
  if (input.referenceImages && input.referenceImages.length > 0)
    throw new ImageCreateError("UNSUPPORTED_REFERENCE_MODE", "the generation provider has no image-reference mode; referenceImages are not supported by engineering.image.create v1");
  const prompt = requirePrompt(input);
  validateGenerationDimensions(input);
  const output = requireOutput(input, true)!;
  const count = input.action === "variation" ? (input.count ?? 2) : (input.count ?? 1);
  if (input.action === "variation" && count < 2) throw new ImageCreateError("INPUT_INVALID", "variation requires count >= 2");
  for (let index = 1; index <= count; index++) {
    const styleHint = input.action === "variation" ? input.styleHints?.[index - 1] : undefined;
    const composedPrompt = [prompt, styleHint].filter(Boolean).join(", ");
    const finalPrompt = input.action === "background" ? `background only (no subject, no product, no text, no watermark): ${composedPrompt}` : composedPrompt;
    const itemPath = count > 1 ? withOutputIndex(output.path, index) : output.path;
    try {
      const result = await generateDeliverExport({ prompt: finalPrompt, width: input.width, height: input.height, model: input.model }, { path: itemPath, format: output.format }, input.compose === true, deps, ctx);
      const exportInfo = exportOf(result);
      ctx.outputs.push({ index, ok: true, path: itemPath, format: output.format, ...(exportInfo ? { export: exportInfo } : {}) });
    } catch (error) {
      if (count === 1) throw error;
      const code = error instanceof ImageCreateError ? error.code : "GENERATION_FAILED";
      const message = error instanceof Error ? error.message : "generation item failed";
      ctx.outputs.push({ index, ok: false, path: itemPath, code, message });
      ctx.warnings.push(`item ${index} failed with ${code}`);
    }
  }
  const failures = ctx.outputs.filter((item) => item.ok === false);
  if (failures.length === ctx.outputs.length) {
    const first = failures[0] as { code?: string; message?: string } | undefined;
    return finish("error", { code: first?.code ?? "GENERATION_FAILED", message: first?.message ?? "all generation items failed" });
  }
  if (failures.length > 0) return finish("partial", { code: "PARTIAL_GENERATION", message: `${failures.length} of ${ctx.outputs.length} items failed` });
  return finish("ok");
}

async function runProduct(input: ImageCreateInput, deps: ImageCreateDeps, ctx: RunContext, finish: Finish): Promise<Record<string, unknown>> {
  const output = requireOutput(input, true)!;
  if (!input.product) throw new ImageCreateError("INPUT_INVALID", "action product requires product.path");
  validateGenerationDimensions(input);
  const canvas = input.canvas ?? null;
  const scenePrompt = input.prompt?.trim() ?? "";
  let backgroundUrl: string | null = null;
  if (canvas && scenePrompt.length > 0) {
    const size = providerBackgroundSize(canvas);
    backgroundUrl = await generateAndStage({ prompt: scenePrompt, width: size.width, height: size.height, model: input.model }, deps, ctx);
  }
  if (canvas) {
    const created = await editStep(deps, { action: "document", document: { op: "create", width: canvas.width, height: canvas.height } }, "create-document");
    if (!created.ok) throw mapEditFailure("create-document", created);
    ctx.operationsApplied.push("create-document");
    ctx.document = { opened: true, width: canvas.width, height: canvas.height, source: backgroundUrl ? "generated-scene" : "blank" };
  } else {
    const opened = await editStep(deps, { action: "document", document: { op: "open", path: input.product.path } }, "open-input:product");
    if (!opened.ok) throw mapEditFailure("open-input:product", opened);
    ctx.operationsApplied.push("open-input:product");
    ctx.document = { opened: true, source: "product" };
  }
  const elements: ElementInput[] = [];
  if (backgroundUrl && canvas) {
    elements.push({ type: "image", path: backgroundUrl, position: { x: 0, y: 0 }, width: canvas.width, height: canvas.height });
  }
  if (canvas) elements.push(productElement(input.product, canvas));
  if (input.logo) elements.push(logoElement(input.logo, canvas));
  if (elements.length > 0) {
    const composed = await editStep(deps, { action: "compose", elements }, "compose");
    if (!composed.ok) throw mapEditFailure("compose", composed, [input.product.path, input.logo?.path ?? ""]);
    ctx.operationsApplied.push("compose");
  }
  const exported = await editStep(deps, { action: "export", output: { path: output.path, format: output.format, overwrite: true } }, "export");
  if (!exported.ok) throw mapEditFailure("export", exported);
  ctx.operationsApplied.push(`export:${output.format}`);
  const exportInfo = exportOf(exported.result);
  ctx.outputs.push({ index: 1, ok: true, path: output.path, format: output.format, ...(exportInfo ? { export: exportInfo } : {}) });
  return finish("ok");
}

async function runCampaign(input: ImageCreateInput, deps: ImageCreateDeps, ctx: RunContext, finish: Finish): Promise<Record<string, unknown>> {
  if (!input.canvas) throw new ImageCreateError("INPUT_INVALID", "action campaign requires canvas");
  const output = requireOutput(input, true)!;
  validateGenerationDimensions(input);
  const canvas = input.canvas;
  const concept = input.concept?.trim() ?? "";
  const backgroundPrompt = `professional advertising key visual background${concept.length > 0 ? `, ${concept}` : ""}, empty clean stage reserved for product and text, no product, no text, no watermark`;
  const size = providerBackgroundSize(canvas);
  const backgroundUrl = await generateAndStage({ prompt: backgroundPrompt, width: size.width, height: size.height, model: input.model }, deps, ctx);
  const created = await editStep(deps, { action: "document", document: { op: "create", width: canvas.width, height: canvas.height } }, "create-document");
  if (!created.ok) throw mapEditFailure("create-document", created);
  ctx.operationsApplied.push("create-document");
  ctx.document = { opened: true, width: canvas.width, height: canvas.height, source: "generated-background" };
  const elements: ElementInput[] = [{ type: "image", path: backgroundUrl, position: { x: 0, y: 0 }, width: canvas.width, height: canvas.height }];
  if (input.product) elements.push(productElement(input.product, canvas));
  if (input.logo) elements.push(logoElement(input.logo, canvas));
  const headline = input.headline?.trim();
  const subheadline = input.subheadline?.trim();
  const cta = input.cta?.trim();
  if (headline) elements.push(textElement(headline, canvas, 0.775, 0.06));
  if (subheadline) elements.push(textElement(subheadline, canvas, 0.855, 0.035));
  if (cta) elements.push(textElement(cta, canvas, 0.915, 0.03));
  const composed = await editStep(deps, { action: "compose", elements }, "compose");
  if (!composed.ok) throw mapEditFailure("compose", composed, [input.product?.path ?? "", input.logo?.path ?? ""]);
  ctx.operationsApplied.push("compose");
  const exported = await editStep(deps, { action: "export", output: { path: output.path, format: output.format, overwrite: true } }, "export");
  if (!exported.ok) throw mapEditFailure("export", exported);
  ctx.operationsApplied.push(`export:${output.format}`);
  const exportInfo = exportOf(exported.result);
  ctx.outputs.push({ index: 1, ok: true, path: output.path, format: output.format, ...(exportInfo ? { export: exportInfo } : {}) });
  return finish("ok");
}

async function runCompose(input: ImageCreateInput, deps: ImageCreateDeps, ctx: RunContext, finish: Finish): Promise<Record<string, unknown>> {
  if (!input.canvas) throw new ImageCreateError("INPUT_INVALID", "action compose requires canvas");
  const mapped = (input.elements ?? []).map((element, index) => mapComposeElement(element, index));
  if (mapped.length === 0) throw new ImageCreateError("INPUT_INVALID", "action compose requires elements");
  const output = requireOutput(input, false);
  const created = await editStep(deps, { action: "document", document: { op: "create", width: input.canvas.width, height: input.canvas.height } }, "create-document");
  if (!created.ok) throw mapEditFailure("create-document", created);
  ctx.operationsApplied.push("create-document");
  ctx.document = { opened: true, width: input.canvas.width, height: input.canvas.height, layers: mapped.length };
  const composed = await editStep(deps, { action: "compose", elements: mapped }, "compose");
  if (!composed.ok) throw mapEditFailure("compose", composed, input.elements?.map((element) => element.path ?? "") ?? []);
  ctx.operationsApplied.push("compose");
  if (output) {
    const exported = await editStep(deps, { action: "export", output: { path: output.path, format: output.format, overwrite: true } }, "export");
    if (!exported.ok) throw mapEditFailure("export", exported);
    ctx.operationsApplied.push(`export:${output.format}`);
    const exportInfo = exportOf(exported.result);
    ctx.outputs.push({ index: 1, ok: true, path: output.path, format: output.format, ...(exportInfo ? { export: exportInfo } : {}) });
  } else {
    ctx.warnings.push("no outputPath provided: composition stays open as an editable Photopea document (preview not exported)");
  }
  return finish("ok");
}

export async function runImageCreate(toolName: string, input: ImageCreateInput, deps: ImageCreateDeps = {}): Promise<Record<string, unknown>> {
  void toolName;
  const ctx: RunContext = { outputs: [], generatedAssets: [], operationsApplied: [], warnings: [], document: null };
  const finish: Finish = (status, extra = {}) => ({
    status,
    action: input.action,
    outputs: ctx.outputs,
    generatedAssets: ctx.generatedAssets,
    ...(ctx.document ? { document: ctx.document } : {}),
    operationsApplied: ctx.operationsApplied,
    ...(ctx.warnings.length > 0 ? { warnings: ctx.warnings } : {}),
    ...extra
  });
  try {
    switch (input.action) {
      case "generate":
      case "background":
      case "scene":
      case "variation":
        return await runGenerationFamily(input, deps, ctx, finish);
      case "product":
        return await runProduct(input, deps, ctx, finish);
      case "campaign":
        return await runCampaign(input, deps, ctx, finish);
      case "compose":
        return await runCompose(input, deps, ctx, finish);
    }
  } catch (error) {
    if (error instanceof ImageCreateError) return finish("error", { code: error.code, message: error.message });
    return finish("error", { code: "IMAGE_CREATE_FAILED", message: error instanceof Error ? error.message : "unexpected failure" });
  }
}
