/**
 * ArchitectureProposalEngine.ts — Sprint 6.2.3
 * Generates a full Architecture Proposal whenever a structural change is detected.
 */

import { CORE_IMMUTABLE } from "./AATypes";
import type { ArchitectureProposal, BreakingChange, BreakingChangeLevel } from "./AATypes";
import type { ArchitectureSnapshot } from "./AATypes";

let _seq = 0;
function makeId(): string { return `aprop_${Date.now()}_${++_seq}`; }

const CORE_SET = new Set(CORE_IMMUTABLE);

export class ArchitectureProposalEngine {
  generate(
    objective: string,
    snapshot: ArchitectureSnapshot,
    affectedComponents: string[],
    breakingChanges: BreakingChange[],
  ): ArchitectureProposal {
    const coreHit = affectedComponents.filter(c => CORE_SET.has(c));
    const hasBlocked = breakingChanges.some(c => c.autoBlocked);
    const maxLevel = this._maxLevel(breakingChanges);

    const requiresApproval = coreHit.length > 0 || hasBlocked || maxLevel === "HIGH" || maxLevel === "CRITICAL";

    const advantages = this._buildAdvantages(objective, breakingChanges);
    const risks      = this._buildRisks(coreHit, breakingChanges);
    const alternatives = this._buildAlternatives(objective);

    const confidence = this._scoreConfidence(coreHit.length, breakingChanges.length, snapshot.kgReady);

    return {
      id:                   makeId(),
      objective,
      problem:              `Engineering change requested: "${objective}"`,
      currentArchitecture:  `${snapshot.modules.length} modules, ${snapshot.singletons.length} singletons, ${snapshot.connectors.length} connectors, ${snapshot.kgEntityCount} KG entities`,
      proposedArchitecture: `Proposed modification affecting: ${affectedComponents.join(", ") || "no components specified"}`,
      advantages,
      risks,
      alternatives,
      migration:            requiresApproval ? "Full migration plan generated by MigrationPlanner" : "No migration required",
      rollback:             "Rollback plan auto-generated before any implementation",
      affectedComponents,
      coreComponentsHit:    coreHit,
      estimatedComplexity:  maxLevel,
      confidenceScore:      confidence,
      breakingChanges,
      requiresApproval,
      status:               "PENDING",
      createdAt:            Date.now(),
      approvedAt:           null,
      rejectedAt:           null,
      rejectionReason:      null,
    };
  }

  private _maxLevel(changes: BreakingChange[]): BreakingChangeLevel {
    const order: BreakingChangeLevel[] = ["SAFE", "LOW", "MEDIUM", "HIGH", "CRITICAL"];
    let max = 0;
    for (const c of changes) {
      const i = order.indexOf(c.level);
      if (i > max) max = i;
    }
    return order[max];
  }

  private _buildAdvantages(objective: string, changes: BreakingChange[]): string[] {
    const adv = [`Achieves the stated objective: "${objective.slice(0, 60)}"`];
    if (changes.length === 0) adv.push("Zero breaking changes detected — safe to implement");
    if (!changes.some(c => c.autoBlocked)) adv.push("No auto-blocked breaking changes");
    adv.push("Architecture Proposal ensures full traceability");
    adv.push("Feature Flag provides safe rollout and instant rollback");
    return adv;
  }

  private _buildRisks(coreHit: string[], changes: BreakingChange[]): string[] {
    const risks: string[] = [];
    if (coreHit.length > 0) risks.push(`Core component(s) affected: ${coreHit.join(", ")} — regression probability elevated`);
    const blocked = changes.filter(c => c.autoBlocked);
    if (blocked.length > 0) risks.push(`${blocked.length} auto-blocked breaking change(s): ${blocked.map(c => c.component).join(", ")}`);
    if (changes.length === 0 && coreHit.length === 0) risks.push("No significant risks identified");
    risks.push("Regression Shield must pass before any implementation proceeds");
    return risks;
  }

  private _buildAlternatives(objective: string): string[] {
    return [
      "Implement incrementally behind Feature Flag",
      "Extend existing component instead of modifying Core",
      "Create adapter layer to preserve backward compatibility",
      "Defer to next sprint after Architecture Review",
    ];
  }

  private _scoreConfidence(coreHit: number, breakingCount: number, kgReady: boolean): number {
    let score = 100;
    score -= coreHit     * 15;
    score -= breakingCount * 8;
    if (!kgReady) score -= 10;
    return Math.max(10, Math.min(100, score));
  }
}