// engineering.image.create unit tests — deterministic, dependency-injected only.
// No network, no real Photopea executor, no real Cloudflare call, no secrets.
// Covers: strict schema (raw execution structurally impossible), the 7 actions,
// fail-closed error mapping, partial-variation honesty, asset delivery route,
// credential resolution (env/file/fail-closed) and secret-free results.
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { strict as assert } from "node:assert";
import {
  IMAGE_ASSET_PATH_PREFIX,
  ImageCreateError,
  imageAssetCount,
  imageCreateInputSchema,
  putGeneratedAsset,
  resolveGenerationCredential,
  runImageCreate,
  serveImageAsset,
  type GenerationRequest,
  type ImageCreateInput
} from "../src/imageCreate.ts";
import type { ImageEditInput } from "../src/imageEdit.ts";

type EditRule = { when: (input: ImageEditInput) => boolean; code?: string; message?: string; result?: Record<string, unknown> };
function fakeEdit(rules: EditRule[] = []) {
  const calls: ImageEditInput[] = [];
  const edit = async (input: ImageEditInput) => {
    calls.push(input);
    const rule = rules.find((candidate) => candidate.when(input));
    if (!rule) return { status: "ok", action: input.action, applied: [], changed: true };
    if (rule.code) return { status: "error", action: input.action, code: rule.code, message: rule.message ?? "executor rejected" };
    return { status: "ok", action: input.action, ...(rule.result ?? {}) };
  };
  return { calls, edit };
}
function fakeGenerate(model = "@cf/black-forest-labs/flux-1-schnell") {
  const calls: GenerationRequest[] = [];
  const generate = async (request: GenerationRequest) => {
    calls.push(request);
    return { bytes: Buffer.alloc(256, 7), contentType: "image/jpeg", model };
  };
  return { calls, generate };
}
function baseDeps(generate: ReturnType<typeof fakeGenerate>["generate"], edit: ReturnType<typeof fakeEdit>["edit"]) {
  return { generate, edit, putAsset: () => "asset-1", publicBaseUrl: "https://mcp.test" };
}
const isOpenDocument = (input: ImageEditInput) => input.action === "document" && input.document?.op === "open";
const isExport = (input: ImageEditInput) => input.action === "export";

test("schema: strict — raw execution channels are structurally impossible", () => {
  const base = { action: "compose", canvas: { width: 1024, height: 1024 }, elements: [{ type: "text", text: "x" }] };
  for (const key of ["script", "toolName", "jsonrpc", "shell", "command", "url", "steps", "tool", "rawArgs"]) {
    const candidate = { ...base, [key]: "inject" } as unknown as Record<string, unknown>;
    assert.equal(imageCreateInputSchema.safeParse(candidate).success, false, `key ${key} must be rejected`);
  }
  assert.equal(imageCreateInputSchema.safeParse({ action: "nonsense" }).success, false);
});

test("schema: minimal payload for each of the 7 high-level actions parses", () => {
  for (const action of ["generate", "background", "scene", "product", "campaign", "compose", "variation"] as const) {
    assert.equal(imageCreateInputSchema.safeParse({ action }).success, true, action);
  }
  assert.equal(imageCreateInputSchema.safeParse({ action: "generate", prompt: "x", outputPath: "C:/a.png", width: 1024, height: 1024, model: "flux-1-schnell", count: 2 }).success, true);
});

test("generate: happy path stages the generated asset over HTTPS and exports locally, with no secrets and no blobs in the result", async () => {
  const gen = fakeGenerate();
  const { calls, edit } = fakeEdit();
  const result = await runImageCreate("engineering.image.create", { action: "generate", prompt: "a red apple on white", outputPath: "C:/tmp/art.png" }, baseDeps(gen.generate, edit));
  assert.equal(result.status, "ok");
  assert.equal(gen.calls.length, 1);
  assert.equal(calls.length, 2);
  assert.equal(calls[0].action, "document");
  assert.equal(calls[0].document?.op, "open");
  assert.equal(calls[0].document?.path, "https://mcp.test/image-asset/asset-1");
  assert.equal(calls[1].action, "export");
  assert.equal(calls[1].output?.path, "C:/tmp/art.png");
  assert.equal(calls[1].output?.overwrite, true);
  const outputs = result.outputs as Array<Record<string, unknown>>;
  assert.equal(outputs.length, 1);
  assert.equal(outputs[0].ok, true);
  assert.equal(outputs[0].path, "C:/tmp/art.png");
  const serialized = JSON.stringify(result);
  assert.ok(!serialized.includes("apiToken"));
  assert.ok(!serialized.includes("Bearer"));
  assert.ok(!serialized.includes("BwcHBw")); // no base64 blob of the generated bytes may leak into the result
  const ops = result.operationsApplied as string[];
  assert.ok(ops.some((op) => op.startsWith("generate:")));
  assert.ok(ops.includes("open:generated-asset"));
  assert.ok(ops.includes("export:png"));
});

test("generate: missing credential fails closed with GENERATION_PROVIDER_UNAVAILABLE (no default generation dep)", async () => {
  const { calls, edit } = fakeEdit();
  const result = await runImageCreate("engineering.image.create", { action: "generate", prompt: "x", outputPath: "C:/a.png" }, { credentialLoader: async () => null, edit });
  assert.equal(result.status, "error");
  assert.equal(result.code, "GENERATION_PROVIDER_UNAVAILABLE");
  assert.equal(calls.length, 0);
});

test("generate: referenceImages fail closed with UNSUPPORTED_REFERENCE_MODE and no generation attempt", async () => {
  const gen = fakeGenerate();
  const result = await runImageCreate("engineering.image.create", { action: "generate", prompt: "x", outputPath: "C:/a.png", referenceImages: ["C:/ref.png"] }, baseDeps(gen.generate, fakeEdit().edit));
  assert.equal(result.status, "error");
  assert.equal(result.code, "UNSUPPORTED_REFERENCE_MODE");
  assert.equal(gen.calls.length, 0);
});

test("generate: provider-unsafe dimensions fail closed with INVALID_DIMENSIONS (runtime) while the schema stays looser", async () => {
  const gen = fakeGenerate();
  const deps = baseDeps(gen.generate, fakeEdit().edit);
  assert.equal(imageCreateInputSchema.safeParse({ action: "generate", prompt: "x", outputPath: "C:/a.png", width: 300 }).success, true);
  assert.equal(imageCreateInputSchema.safeParse({ action: "generate", prompt: "x", outputPath: "C:/a.png", width: 5000 }).success, false);
  const tooSmall = await runImageCreate("engineering.image.create", { action: "generate", prompt: "x", outputPath: "C:/a.png", width: 300 }, deps);
  assert.equal(tooSmall.status, "error");
  assert.equal(tooSmall.code, "INVALID_DIMENSIONS");
  const notMultiple = await runImageCreate("engineering.image.create", { action: "generate", prompt: "x", outputPath: "C:/a.png", height: 1000 + 4 }, deps);
  assert.equal(notMultiple.code, "INVALID_DIMENSIONS");
  assert.equal(gen.calls.length, 0);
});

test("generate: relay-level failures pass through unchanged (LOCAL_EDITOR_OFFLINE)", async () => {
  const gen = fakeGenerate();
  const { edit } = fakeEdit([{ when: isOpenDocument, code: "LOCAL_EDITOR_OFFLINE" }]);
  const result = await runImageCreate("engineering.image.create", { action: "generate", prompt: "x", outputPath: "C:/a.png" }, baseDeps(gen.generate, edit));
  assert.equal(result.status, "error");
  assert.equal(result.code, "LOCAL_EDITOR_OFFLINE");
});

test("generate: export failure maps to EXPORT_FAILED; generated-open failure maps to COMPOSITION_FAILED", async () => {
  const gen = fakeGenerate();
  const exportFail = await runImageCreate("engineering.image.create", { action: "generate", prompt: "x", outputPath: "C:/a.png" }, baseDeps(gen.generate, fakeEdit([{ when: isExport, code: "PHOTOPEA_ERROR" }]).edit));
  assert.equal(exportFail.status, "error");
  assert.equal(exportFail.code, "EXPORT_FAILED");
  const openFail = await runImageCreate("engineering.image.create", { action: "generate", prompt: "x", outputPath: "C:/a.png" }, baseDeps(fakeGenerate().generate, fakeEdit([{ when: isOpenDocument, code: "PHOTOPEA_ERROR" }]).edit));
  assert.equal(openFail.code, "COMPOSITION_FAILED");
});

test("background: deterministic template wraps the user prompt", async () => {
  const gen = fakeGenerate();
  await runImageCreate("engineering.image.create", { action: "background", prompt: "clinical white laboratory", outputPath: "C:/bg.png" }, baseDeps(gen.generate, fakeEdit().edit));
  assert.equal(gen.calls.length, 1);
  assert.ok(gen.calls[0].prompt.startsWith("background only"));
  assert.ok(gen.calls[0].prompt.includes("clinical white laboratory"));
});

test("variation: count with styleHints produces indexed outputs and per-item prompts", async () => {
  const gen = fakeGenerate();
  const { calls, edit } = fakeEdit();
  const input: ImageCreateInput = { action: "variation", prompt: "premium clinical product art", count: 3, styleHints: ["studio light", "outdoor golden hour"], outputPath: "C:/camp/art.png" };
  const result = await runImageCreate("engineering.image.create", input, baseDeps(gen.generate, edit));
  assert.equal(result.status, "ok");
  assert.equal(gen.calls.length, 3);
  assert.ok(gen.calls[0].prompt.includes("studio light"));
  assert.ok(gen.calls[1].prompt.includes("outdoor golden hour"));
  assert.ok(gen.calls[2].prompt.endsWith("premium clinical product art"));
  const outputs = result.outputs as Array<Record<string, unknown>>;
  assert.deepEqual(outputs.map((item) => item.path), ["C:/camp/art-1.png", "C:/camp/art-2.png", "C:/camp/art-3.png"]);
  assert.ok(outputs.every((item) => item.ok === true));
  const exportCalls = calls.filter((call) => call.action === "export");
  assert.equal(exportCalls.length, 3);
});

test("variation: partial failure is reported honestly (status partial + warnings + per-item ok)", async () => {
  const gen = fakeGenerate();
  const { edit } = fakeEdit([{ when: (input) => isExport(input) && (input.output?.path ?? "").includes("-2"), code: "PHOTOPEA_ERROR" }]);
  const result = await runImageCreate("engineering.image.create", { action: "variation", prompt: "x", count: 3, outputPath: "C:/camp/art.png" }, baseDeps(gen.generate, edit));
  assert.equal(result.status, "partial");
  assert.equal(result.code, "PARTIAL_GENERATION");
  const outputs = result.outputs as Array<Record<string, unknown>>;
  assert.equal(outputs.length, 3);
  assert.equal(outputs[0].ok, true);
  assert.equal(outputs[1].ok, false);
  assert.equal(outputs[2].ok, true);
  assert.equal((result.warnings as string[]).length, 1);
});

test("variation: count below 2 is rejected deterministically", async () => {
  const result = await runImageCreate("engineering.image.create", { action: "variation", prompt: "x", count: 1, outputPath: "C:/a.png" }, baseDeps(fakeGenerate().generate, fakeEdit().edit));
  assert.equal(result.status, "error");
  assert.equal(result.code, "INPUT_INVALID");
});

test("campaign: deterministic composition — background, product, logo, three texts, export", async () => {
  const gen = fakeGenerate();
  const { calls, edit } = fakeEdit();
  const input: ImageCreateInput = {
    action: "campaign",
    canvas: { width: 1080, height: 1350 },
    concept: "premium clinical",
    product: { path: "C:/assets/product.png" },
    logo: { path: "C:/assets/logo.png" },
    headline: "NAC 600 mg",
    subheadline: "Mucolytic support",
    cta: "Ask your pharmacist",
    outputPath: "C:/out/instagram.png"
  };
  const result = await runImageCreate("engineering.image.create", input, baseDeps(gen.generate, edit));
  assert.equal(result.status, "ok");
  assert.equal(gen.calls.length, 1);
  assert.deepEqual({ width: gen.calls[0].width, height: gen.calls[0].height }, { width: 816, height: 1024 });
  assert.ok(gen.calls[0].prompt.includes("premium clinical"));
  assert.ok(gen.calls[0].prompt.includes("no text"));
  assert.equal(calls.length, 3);
  assert.equal(calls[0].action, "document");
  assert.deepEqual({ width: calls[0].document?.width, height: calls[0].document?.height }, { width: 1080, height: 1350 });
  assert.equal(calls[1].action, "compose");
  const elements = calls[1].elements ?? [];
  assert.equal(elements.length, 6);
  assert.equal(elements[0].type, "image");
  assert.equal(elements[0].path, "https://mcp.test/image-asset/asset-1");
  assert.deepEqual(elements[0].position, { x: 0, y: 0 });
  assert.equal(elements[1].path, "C:/assets/product.png");
  assert.equal(elements[2].path, "C:/assets/logo.png");
  assert.equal(elements[3].type, "text");
  assert.equal(elements[3].text, "NAC 600 mg");
  assert.ok((elements[4].position?.y ?? 0) > (elements[3].position?.y ?? 0));
  assert.ok((elements[5].position?.y ?? 0) > (elements[4].position?.y ?? 0));
  assert.equal(calls[2].action, "export");
  assert.equal(calls[2].output?.path, "C:/out/instagram.png");
  const ops = result.operationsApplied as string[];
  for (const expected of ["create-document", "compose", "export:png"]) assert.ok(ops.includes(expected));
});

test("campaign: missing canvas or outputPath fails closed with INPUT_INVALID", async () => {
  const gen = fakeGenerate();
  const deps = baseDeps(gen.generate, fakeEdit().edit);
  const noCanvas = await runImageCreate("engineering.image.create", { action: "campaign", outputPath: "C:/a.png" } as ImageCreateInput, deps);
  assert.equal(noCanvas.code, "INPUT_INVALID");
  const noOutput = await runImageCreate("engineering.image.create", { action: "campaign", canvas: { width: 1080, height: 1350 } } as ImageCreateInput, deps);
  assert.equal(noOutput.code, "INPUT_INVALID");
  assert.equal(gen.calls.length, 0);
});

test("compose: maps elements in caller order into ONE image.edit compose call; export optional", async () => {
  const gen = fakeGenerate();
  const { calls, edit } = fakeEdit();
  const input: ImageCreateInput = {
    action: "compose",
    canvas: { width: 1000, height: 1000 },
    elements: [
      { type: "background", path: "C:/bg.png" },
      { type: "text", text: "Headline", fontSize: 60, color: "#ffffff", position: { x: 60, y: 800 } },
      { type: "shape", shape: "rectangle", position: { x: 0, y: 0 }, width: 100, height: 50, color: "#336699" }
    ],
    outputPath: "C:/out/composed.png"
  };
  const result = await runImageCreate("engineering.image.create", input, baseDeps(gen.generate, edit));
  assert.equal(result.status, "ok");
  assert.equal(gen.calls.length, 0);
  assert.equal(calls.length, 3);
  const elements = calls[1].elements ?? [];
  assert.equal(elements.length, 3);
  assert.equal(elements[0].type, "image");
  assert.equal(elements[0].path, "C:/bg.png");
  assert.equal(elements[1].type, "text");
  assert.equal(elements[1].fontSize, 60);
  assert.equal(elements[2].type, "shape");
  assert.equal(elements[2].width, 100);
  assert.equal(calls[2].action, "export");
});

test("compose: without outputPath stays editable and reports a warning instead of a preview", async () => {
  const input: ImageCreateInput = { action: "compose", canvas: { width: 800, height: 600 }, elements: [{ type: "generatedImage", path: "C:/gen.png" }] };
  const result = await runImageCreate("engineering.image.create", input, baseDeps(fakeGenerate().generate, fakeEdit().edit));
  assert.equal(result.status, "ok");
  assert.equal((result.outputs as unknown[]).length, 0);
  assert.equal((result.warnings as string[]).length, 1);
});

test("compose: missing canvas, empty mapping and missing element path fail closed", async () => {
  const deps = baseDeps(fakeGenerate().generate, fakeEdit().edit);
  const noCanvas = await runImageCreate("engineering.image.create", { action: "compose", elements: [{ type: "background", path: "C:/b.png" }] } as ImageCreateInput, deps);
  assert.equal(noCanvas.code, "INPUT_INVALID");
  const noPath = await runImageCreate("engineering.image.create", { action: "compose", canvas: { width: 800, height: 600 }, elements: [{ type: "background" }] } as ImageCreateInput, deps);
  assert.equal(noPath.code, "INPUT_INVALID");
  const noText = await runImageCreate("engineering.image.create", { action: "compose", canvas: { width: 800, height: 600 }, elements: [{ type: "text" }] } as ImageCreateInput, deps);
  assert.equal(noText.code, "INPUT_INVALID");
});

test("product: without canvas the real product photo is the base document (preserved, never regenerated)", async () => {
  const gen = fakeGenerate();
  const { calls, edit } = fakeEdit();
  const result = await runImageCreate("engineering.image.create", { action: "product", product: { path: "C:/assets/product.png" }, logo: { path: "C:/assets/logo.png" }, outputPath: "C:/out/preview.png" }, baseDeps(gen.generate, edit));
  assert.equal(result.status, "ok");
  assert.equal(gen.calls.length, 0);
  assert.equal(calls[0].action, "document");
  assert.equal(calls[0].document?.path, "C:/assets/product.png");
  assert.equal((calls[1].elements ?? []).length, 1);
  assert.equal(calls[1].elements?.[0].path, "C:/assets/logo.png");
  assert.equal(calls[2].action, "export");
  const ops = result.operationsApplied as string[];
  assert.ok(ops.includes("open-input:product"));
});

test("product: with canvas + context prompt generates a scene and mounts product + background", async () => {
  const gen = fakeGenerate();
  const { calls, edit } = fakeEdit();
  const result = await runImageCreate("engineering.image.create", {
    action: "product",
    prompt: "premium gym interior",
    product: { path: "C:/assets/product.png", placement: { width: 400, height: 400, position: { x: 312, y: 300 } } },
    canvas: { width: 1024, height: 1024 },
    outputPath: "C:/out/scene.png"
  }, baseDeps(gen.generate, edit));
  assert.equal(result.status, "ok");
  assert.equal(gen.calls.length, 1);
  assert.deepEqual({ width: gen.calls[0].width, height: gen.calls[0].height }, { width: 1024, height: 1024 });
  const elements = calls[1].elements ?? [];
  assert.equal(elements.length, 2);
  assert.equal(elements[0].type, "image");
  assert.equal(elements[0].path, "https://mcp.test/image-asset/asset-1");
  assert.equal(elements[1].path, "C:/assets/product.png");
  assert.deepEqual(elements[1].position, { x: 312, y: 300 });
});

test("product: failed open of the real product asset maps to INPUT_ASSET_NOT_FOUND", async () => {
  const { edit } = fakeEdit([{ when: (input) => isOpenDocument(input) && input.document?.path === "C:/missing.png", code: "PHOTOPEA_ERROR" }]);
  const result = await runImageCreate("engineering.image.create", { action: "product", product: { path: "C:/missing.png" }, outputPath: "C:/out.png" }, baseDeps(fakeGenerate().generate, edit));
  assert.equal(result.status, "error");
  assert.equal(result.code, "INPUT_ASSET_NOT_FOUND");
});

test("product: missing product.path fails closed with INPUT_INVALID", async () => {
  const result = await runImageCreate("engineering.image.create", { action: "product", outputPath: "C:/out.png" } as ImageCreateInput, baseDeps(fakeGenerate().generate, fakeEdit().edit));
  assert.equal(result.code, "INPUT_INVALID");
});

test("outputPath: unsupported extension and missing path fail closed with INPUT_INVALID", async () => {
  const deps = baseDeps(fakeGenerate().generate, fakeEdit().edit);
  const gif = await runImageCreate("engineering.image.create", { action: "generate", prompt: "x", outputPath: "C:/a.gif" }, deps);
  assert.equal(gif.code, "INPUT_INVALID");
  const noExt = await runImageCreate("engineering.image.create", { action: "generate", prompt: "x", outputPath: "C:/a" }, deps);
  assert.equal(noExt.code, "INPUT_INVALID");
  const missing = await runImageCreate("engineering.image.create", { action: "generate", prompt: "x" } as ImageCreateInput, deps);
  assert.equal(missing.code, "INPUT_INVALID");
});

test("credential resolution: env wins over file, file works alone, none fails closed — values never logged", async () => {
  const dir = await mkdtemp(join(tmpdir(), "imagecreate-test-"));
  const file = join(dir, "cred.json");
  await writeFile(file, JSON.stringify({ apiToken: "file-token-value", accountId: "file-account" }), "utf8");
  try {
    const fromEnv = await resolveGenerationCredential({ env: { CLOUDFLARE_API_TOKEN: "env-token", CLOUDFLARE_ACCOUNT_ID: "env-account" } });
    assert.equal(fromEnv?.accountId, "env-account");
    const fromFile = await resolveGenerationCredential({ env: {}, file });
    assert.equal(fromFile?.accountId, "file-account");
    assert.equal(fromFile?.apiToken, "file-token-value");
    const none = await resolveGenerationCredential({ env: {}, file: join(dir, "missing.json") });
    assert.equal(none, null);
    const badJson = await resolveGenerationCredential({ env: {}, file: join(tmpdir(), "imagecreate-test-does-not-exist") });
    assert.equal(badJson, null);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("asset delivery route: GET serves staged bytes, TTL expiry 404s, non-asset requests pass through", () => {
  const id = putGeneratedAsset(Buffer.from("hello-bytes"), "image/jpeg", 1000);
  const hit = serveImageAsset("GET", `${IMAGE_ASSET_PATH_PREFIX}${id}`, 2000);
  assert.equal(hit.handled, true);
  if (hit.handled) {
    assert.equal(hit.status, 200);
    assert.equal(hit.contentType, "image/jpeg");
    assert.deepEqual(hit.bytes, Buffer.from("hello-bytes"));
  }
  const unknown = serveImageAsset("GET", `${IMAGE_ASSET_PATH_PREFIX}nope`, 2000);
  assert.equal(unknown.handled, true);
  assert.ok(unknown.handled && unknown.status === 404);
  assert.equal(serveImageAsset("POST", `${IMAGE_ASSET_PATH_PREFIX}${id}`, 2000).handled, false);
  assert.equal(serveImageAsset("GET", "/mcp", 2000).handled, false);
  assert.equal(serveImageAsset("GET", "/", 2000).handled, false);
  const beyondTtl = 1000 + 16 * 60_000; // 16 min > the 15-minute asset TTL
  const expired = serveImageAsset("GET", `${IMAGE_ASSET_PATH_PREFIX}${id}`, beyondTtl);
  assert.ok(expired.handled && expired.status === 404); // the expiry lookup itself sweeps the expired asset
  const second = putGeneratedAsset(Buffer.from("a"), "image/jpeg", beyondTtl);
  const third = putGeneratedAsset(Buffer.from("b"), "image/jpeg", beyondTtl);
  assert.notEqual(second, third);
  assert.equal(imageAssetCount(beyondTtl + 1), 2); // only the two fresh assets remain
  assert.equal(imageAssetCount(beyondTtl + 16 * 60_000), 0); // both expired and swept
});

test("error class: ImageCreateError carries a deterministic code", () => {
  const error = new ImageCreateError("GENERATION_FAILED", "provider rejected");
  assert.equal(error.code, "GENERATION_FAILED");
  assert.equal(error.message, "provider rejected");
});
